name: phpstan-evaluate-pr

on:
  pull_request:
    paths:
      - "**/*.php"
      - "composer.json"
      - "composer.lock"
      - "phpstan.neon"
      - ".github/workflows/phpstan-evaluate-pr.yml"

permissions:
  contents: read

concurrency:
  group: phpstan-${{ github.ref }}
  cancel-in-progress: true

jobs:
  evaluate-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          php_extensions: zip intl gd
      - name: Generate review baseline
        run: php -d memory_limit=1G vendor/bin/phpstan analyse --configuration=phpstan.neon --generate-baseline=phpstan-baseline.neon
      - name: Upload review baseline
        uses: actions/upload-artifact@v4
        with:
          name: phpstan-baseline
          path: phpstan-baseline.neon
